export const FuelEntryReportHeaders = [
    'Equipment/Vehicle',
    'Diesel Dia',
    'Diesel Noche',
    'Gasoline Gallons',
    'Oil 15W40',
    'Oil W30Cat',
    'Oil 15W40Cat',
    'Oil 20W50',
    'Oil 85W140',
    'Oil 80W90',
    'Oil 30',
    'Oil ATF',
    'Cooling',
    'Grease',
];
