export const EquipmentsReportHeaders = [
  'Descripcion',
  'Código',
  'Marca',
  'Año',
  'Modelo',
  'Número de serie',
  'Tipo',
  'Placa',
  'Motor - marca',
  'Motor - modelo',
  'Motor - número de serie',
  'Certificado de registro',
  'ID card',
  'Valor de compra',
  'Fecha de recepción',
  'Número de declaración',
  'BL',
  'Carga',
  'Dispositivo de protección',
  'Fecha de expiración de dispositivo de protección',
  'Póliza de seguro',
  'Fecha de expiración de seguro',
  'Fecha de importación',
  'Importación VAT',
  'Importación DAI',
  'Compañía',
  'Estado',
];