export interface Equipment {
  description: string;
  code: string;
  brand: string;
  year: number;
  model: string;
  serial: string;
  type: string;
  plate: string;
  registrationCert: string;
  idCard: string;
  purchaseValue: string;
  receptionDate: string;
  declarationNumber: string;
  bl: string;
  freight: number;
  protectionDevice: string;
  protectionDeviceDateExpiration: string;
  company: string;
  status: string;
  engineBrand: string;
  engineModel: string;
  engineSerial: string;
  insurancePolicy: string;
  insuranceExpirationDate: string;
  importationDate: string;
  importationVat: string;
  importationDai: string;
}